pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo 'Checked out the code successfully.'
                sh 'docker --version'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("my-python-app")
                    echo 'Docker image built successfully.'
                }
            }
        }

        stage('Run Application') {
            steps {
                script {
                    def image = docker.image("my-python-app")
                    sh "docker run -d --name my-python-app -p 8888:5000 ${image.id}"
                }

                sleep 10

                echo "Fetching container logs..."
                sh 'docker logs my-python-app || true'

                echo "Checking application health on port 8888..."
                sh 'curl http://localhost:8888 || true'
            }
            post {
                always {
                    echo "Cleaning up..."
                    sh 'docker stop my-python-app || true'
                    sh 'docker rm my-python-app || true'
                }
            }
        }

        stage('Test') {
            steps {
                echo "Simulated test run here."
                // You can add real test commands like:
                // sh 'pytest tests/'
            }
        }
    }
}